### ISSUE TITLE
Please create a deno version of this plugin

### ISSUE THREAD

**Issue by DevRubicate** [craftamap/esbuild-plugin-html#68]
> There is currently no deno version of this plugin - however, if there is need for it, I will add one - [just open a issue.](https://github.com/craftamap/esbuild-plugin-html/issues/new)

I am using deno for a project with esbuild and need to output my bundle as a single html file. It would be super cool if I could avoid having to use nodejs just to build the bundle.

**Comment by craftamap** [comment]
Hey there!

Since I've written the text into the description, a lot has changed, afaik Deno now supports tons of node apis. Did you try using the plugin with deno ? Is anything actually preventing this from running?

Also, just fyi, this project is not my main priority atm, so I can't promise to take an actual look. :)

**Comment by DevRubicate** [comment]
Oh, I didn't actually try, I'll give it a go.

**Comment by DevRubicate** [comment]
You are right, it works perfectly out of the box! Thanks for the heads up.

**Comment by craftamap** [comment]
Nice, perfect! In this case, I'll update the README the next days. :)
